version: '3.9'

services:
  web-client:
    build: ./web-client
    ports:
      - 3000:3000

  api:
    build: ./api
    ports:
      - 3004:3004
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgres:database_password@database:5432/postgres

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: database_password
    volumes:
      - database-volume:/var/lib/postgresql/data

volumes:
  database-volume: