version: '3.9'

services:
  web-client:
    build:
      context: ./web-client
      target: development
    volumes:
      - ./web-client:/app
      - /app/node_modules
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 3004:3004
    depends_on:
      - database
      - test-database
    environment:
      - DATABASE_URL=postgres://postgres:database_password@database:5432/postgres
      - TEST_DATABASE_URL=postgres://postgres:database_password@test-database:5432/postgres

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: database_password
    volumes:
      - database-volume:/var/lib/postgresql/data

  test-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: database_password

volumes:
  database-volume: