# http
POST http://localhost:3001/wilders HTTP/1.1
content-type: application/json

{
    "name": "arnaud",
    "city": "Londres",
    "skills": [
        {
            "title": "express",
            "votes": 5
        },
        {
            "title": "mongo",
            "votes": 12
        }
    ]
}

###

# http
GET http://localhost:3001/wilders HTTP/1.1

###

# http
GET http://localhost:3001/nexistepas HTTP/1.1

###

# http
DELETE  http://localhost:3001/wilders/arnaud HTTP/1.1
